version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - LANGCHAIN_API_KEY=$LANGCHAIN_API_KEY
      - LANGCHAIN_TRACING_V2=$LANGCHAIN_TRACING_V2
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: /app/node_modules/.bin/nodemon app.js

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
