version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-component
    container_name: ai-component
    restart: unless-stopped
    env_file: .env
    environment:
      - OPEN_AI_API_KEY=$OPEN_AI_API_KEY
      - LANGCHAIN_API_KEY=$LANGCHAIN_API_KEY
      - LANGCHAIN_TRACING_V2=$LANGCHAIN_TRACING_V2
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: /app/node_modules/.bin/nodemon ./dist/App.js

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
