version: "3"

services:
  ai-student-advisor-backend:
    image: ai-student-advisor/backend
    build: .
    container_name: ai-student-advisor-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - ai-student-advisor-default

networks:
  ai-student-advisor-default:
